spring:
  datasource:
    url: jdbc:h2:mem:account_app
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
    properties:
      hibernate.format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
spring-doc:
  swagger-ui:
    path: /swagger-ui.html
server:
  port: 8080
logging:
  level:
    org.springframework.web: DEBUG
