CREATE TABLE tb_account (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   holder_name VARCHAR(255) NOT NULL,
   balance DECIMAL NOT NULL,
   CONSTRAINT pk_tb_account PRIMARY KEY (id)
);

ALTER TABLE tb_account ADD CONSTRAINT uc_tb_account_holder_name UNIQUE (holder_name);